# EXEMPLO de docker-compose para Portainer
# Este é apenas um exemplo para demonstrar a viabilidade
# NÃO substitui a configuração atual do projeto

version: '3.8'

services:
  trustscore-bot-exemplo:
    # Opção 1: Usar imagem Node.js e clonar repositório
    image: node:22-alpine
    working_dir: /app
    command: >
      sh -c "
        apk add --no-cache git wget &&
        git clone https://github.com/samyralmeida/trustscore.git . &&
        npm ci &&
        npm run build &&
        npm start
      "
    
    # Opção 2: Build local (se tiver acesso ao código)
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    
    # Opção 3: Usar imagem pré-buildada (se disponível no Docker Hub)
    # image: samyralmeida/trustscore:latest
    
    container_name: trustscore-bot-exemplo
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      # Token do bot (configurar no Portainer)
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_BOT_USERNAME=${TELEGRAM_BOT_USERNAME}
      # MongoDB da IPMais (mesma configuração atual)
      - MONGODB_CNN=mongodb://ipmais:As5173121220*@mongo.ipmais.com:27077/trustscore_bot?authSource=admin
    networks:
      - trustscore-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/api/karma/total"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Logs persistentes
    volumes:
      - ./logs:/usr/src/app/logs

  # Opcional: Nginx para proxy reverso (desabilitado para evitar problemas)
  # nginx-proxy:
  #   image: nginx:alpine
  #   container_name: trustscore-nginx
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./ssl:/etc/nginx/ssl:ro
  #   networks:
  #     - trustscore-network
  #   depends_on:
  #     - trustscore-bot-exemplo

  # Opcional: Watchtower para auto-updates (desabilitado para evitar problemas)
  # watchtower:
  #   image: containrrr/watchtower
  #   container_name: trustscore-watchtower
  #   restart: unless-stopped
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   environment:
  #     - WATCHTOWER_CLEANUP=true
  #     - WATCHTOWER_POLL_INTERVAL=3600
  #     - WATCHTOWER_INCLUDE_STOPPED=true
  #   command: trustscore-bot-exemplo

networks:
  trustscore-network:
    driver: bridge

# Configurações para Portainer
# Variáveis de ambiente necessárias:
# TELEGRAM_BOT_TOKEN=seu_token_aqui
# TELEGRAM_BOT_USERNAME=seu_bot_username

# Instruções:
# 1. No Portainer, criar nova Stack
# 2. Colar este docker-compose
# 3. Configurar as variáveis de ambiente
# 4. Deploy

# Vantagens desta abordagem:
# - Usa o código direto do Git do Samyr
# - Conecta no MongoDB da IPMais (mesma config atual)
# - Auto-updates com Watchtower
# - Proxy reverso com Nginx
# - Monitoramento via Portainer
# - Logs persistentes
# - Health checks